/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.*;

/**
 *
 * @author Elizabeth
 */
public class add_institucional extends javax.swing.JInternalFrame {

    /**
     * Creates new form add_institucional
     */
    conexion_bd con = new conexion_bd();
    DefaultTableModel modeloTabla = new DefaultTableModel();

    public add_institucional() {
        initComponents();

        txt_inst_direcc.setEnabled(false);
        txt_inst_email.setEnabled(false);
        txt_inst_fono.setEnabled(false);
        txt_inst_inactivo.setEnabled(false);
        txt_inst_activo.setEnabled(false);
        txt_inst_presidente.setEnabled(false);
        txt_inst_razon.setEnabled(false);
        txt_inst_ruc.setEnabled(false);
        txt_inst_secre.setEnabled(false);
        txt_inst_tesorero.setEnabled(false);
        txt_inst_vice.setEnabled(false);

        btn_inst_save.setEnabled(false);
        btn_inst_modifica.setEnabled(false);
        btn_inst_delete.setEnabled(false);

        /**/
        modeloTabla.addColumn("Nro");
        modeloTabla.addColumn("RUC/ID");
        modeloTabla.addColumn("Razon S.");
        modeloTabla.addColumn("Direcc.");
        modeloTabla.addColumn("Email");
        modeloTabla.addColumn("Telf.");
        modeloTabla.addColumn("Presidente");
        modeloTabla.addColumn("VicePresidente");
        modeloTabla.addColumn("Secretario");
        modeloTabla.addColumn("Tesorero");
        modeloTabla.addColumn("Estado");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estado_insti = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_inst_ruc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_inst_direcc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_inst_fono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_inst_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_inst_presidente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_inst_vice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_inst_secre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_inst_tesorero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_inst_razon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_inst_activo = new javax.swing.JRadioButton();
        txt_inst_inactivo = new javax.swing.JRadioButton();
        hidden_id_inst = new javax.swing.JLabel();
        hidden_id_modifi_save = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_inst_list = new javax.swing.JButton();
        btn_inst_new = new javax.swing.JButton();
        btn_inst_save = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_institucion = new javax.swing.JTable();
        btn_inst_modifica = new javax.swing.JButton();
        btn_inst_delete = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS INSTITUCIONALES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("RUC/ID");

        txt_inst_ruc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Direc. Inst.");

        txt_inst_direcc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Telf. Insti");

        txt_inst_fono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Correo. Inst");

        txt_inst_email.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Presidente");

        txt_inst_presidente.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Vicepresidente");

        txt_inst_vice.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setText("Secretario");

        txt_inst_secre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 153));
        jLabel9.setText("Tesorero");

        txt_inst_tesorero.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Razon Social");

        txt_inst_razon.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 0));
        jLabel10.setText("Estado");

        estado_insti.add(txt_inst_activo);
        txt_inst_activo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_inst_activo.setSelected(true);
        txt_inst_activo.setText("Activo");

        estado_insti.add(txt_inst_inactivo);
        txt_inst_inactivo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txt_inst_inactivo.setText("Inactivo");

        hidden_id_inst.setText("jLabel13");

        hidden_id_modifi_save.setText("hidden_id_modifi_save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_inst_razon, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_inst_direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_inst_fono, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel1))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_inst_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_inst_activo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_inst_inactivo))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_inst_email, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(21, 21, 21)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_inst_secre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_inst_tesorero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_inst_presidente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_inst_vice, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hidden_id_inst)
                        .addGap(87, 87, 87)
                        .addComponent(hidden_id_modifi_save)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_inst_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_inst_razon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_inst_direcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_inst_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_inst_fono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_inst_activo)
                            .addComponent(txt_inst_inactivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_inst_presidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_inst_vice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_inst_secre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_inst_tesorero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hidden_id_inst)
                    .addComponent(hidden_id_modifi_save)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(204, 0, 153))); // NOI18N

        btn_inst_list.setBackground(new java.awt.Color(255, 255, 153));
        btn_inst_list.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btn_inst_list.setForeground(new java.awt.Color(0, 153, 51));
        btn_inst_list.setText("Listar Instituciones");
        btn_inst_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inst_listActionPerformed(evt);
            }
        });

        btn_inst_new.setBackground(new java.awt.Color(0, 102, 102));
        btn_inst_new.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btn_inst_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_inst_new.setText("Crear Instituciòn");
        btn_inst_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inst_newActionPerformed(evt);
            }
        });

        btn_inst_save.setBackground(new java.awt.Color(102, 0, 255));
        btn_inst_save.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btn_inst_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_inst_save.setText("Grabar Insituciòn");
        btn_inst_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inst_saveActionPerformed(evt);
            }
        });

        jLabel11.setText("IMG");

        jLabel12.setText("IMG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_inst_list)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_inst_new, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_inst_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_inst_new)
                        .addGap(21, 21, 21)
                        .addComponent(btn_inst_save))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inst_list))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        table_institucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_institucion);

        btn_inst_modifica.setBackground(new java.awt.Color(0, 102, 255));
        btn_inst_modifica.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btn_inst_modifica.setForeground(new java.awt.Color(255, 255, 255));
        btn_inst_modifica.setText("Modificar Institucion");
        btn_inst_modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inst_modificaActionPerformed(evt);
            }
        });

        btn_inst_delete.setBackground(new java.awt.Color(153, 0, 0));
        btn_inst_delete.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btn_inst_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_inst_delete.setText("Inactivar Instituciòn");
        btn_inst_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inst_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_inst_modifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_inst_delete)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inst_modifica)
                    .addComponent(btn_inst_delete))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inst_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inst_listActionPerformed
        btn_inst_modifica.setEnabled(true);
        btn_inst_delete.setEnabled(true);
        Connection c = con.conexion();
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }

        try {
            PreparedStatement pss = null;
            pss = c.prepareStatement("SELECT id,PersonaComercio_cedulaRuc,razonsocial,direccion,email,telefonos,\n"
                    + "presidente,vicepresidente,secretario,tesorero,esta_activo\n"
                    + "FROM billing_proveedor \n"
                    + "WHERE es_institucion =1");

            ResultSet rss = pss.executeQuery();
            while (rss.next()) {
                String act_desc = rss.getString("esta_activo");
                String txt_search = null;
                if (act_desc.equals("1")) {
                    txt_search = "Activo";
                }
                if (act_desc.equals("0")) {
                    txt_search = "Inactivo";
                }
                modeloTabla.addRow(new Object[]{
                    rss.getString("id"),
                    rss.getString("razonsocial"),
                    rss.getString("PersonaComercio_cedulaRuc"),
                    rss.getString("direccion"),
                    rss.getString("email"),
                    rss.getString("telefonos"),
                    rss.getString("presidente"),
                    rss.getString("vicepresidente"),
                    rss.getString("secretario"),
                    rss.getString("tesorero"),
                    txt_search
                });
            }
            this.table_institucion.setModel(modeloTabla);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }
    }//GEN-LAST:event_btn_inst_listActionPerformed

    private void btn_inst_modificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inst_modificaActionPerformed
        int filaEditar = table_institucion.getSelectedRow();
        int numfilas = table_institucion.getSelectedRowCount();
        if (filaEditar >= 0 && numfilas == 1) {
            btn_inst_save.setEnabled(true);
            btn_inst_new.setEnabled(false);
            activa();
            btn_inst_save.setText("Modificar Insituciòn");

            String inst_id = String.valueOf(table_institucion.getValueAt(filaEditar, 0));
            String inst_razon = String.valueOf(table_institucion.getValueAt(filaEditar, 1));
            String inst_ruc = String.valueOf(table_institucion.getValueAt(filaEditar, 2));
            String inst_direcc = String.valueOf(table_institucion.getValueAt(filaEditar, 3));
            String inst_email = String.valueOf(table_institucion.getValueAt(filaEditar, 4));
            String inst_fono = String.valueOf(table_institucion.getValueAt(filaEditar, 5));
            String inst_presidente = String.valueOf(table_institucion.getValueAt(filaEditar, 6));
            String inst_vice = String.valueOf(table_institucion.getValueAt(filaEditar, 7));
            String inst_secre = String.valueOf(table_institucion.getValueAt(filaEditar, 8));
            String inst_tesorero = String.valueOf(table_institucion.getValueAt(filaEditar, 9));
            String activo_inactivo = String.valueOf(table_institucion.getValueAt(filaEditar, 10));

            hidden_id_inst.setText(inst_id);
            hidden_id_modifi_save.setText("1");
            txt_inst_razon.setText(inst_razon);
            txt_inst_ruc.setText(inst_ruc);
            txt_inst_direcc.setText(inst_direcc);
            txt_inst_email.setText(inst_email);
            txt_inst_fono.setText(inst_fono);
            txt_inst_presidente.setText(inst_presidente);
            txt_inst_vice.setText(inst_vice);
            txt_inst_secre.setText(inst_secre);
            txt_inst_tesorero.setText(inst_tesorero);

            if (activo_inactivo.equals("1")) {
                txt_inst_activo.setSelected(true);
            }
            if (activo_inactivo.equals("0")) {
                txt_inst_inactivo.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBE DE SELECCIONAR AL MENOS UN DATO PARA INACTIVAR");
        }
    }//GEN-LAST:event_btn_inst_modificaActionPerformed

    private void btn_inst_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inst_deleteActionPerformed
        int filaEditar = table_institucion.getSelectedRow();
        int numfilas = table_institucion.getSelectedRowCount();
        if (filaEditar >= 0 && numfilas == 1) {
            String id_selec = String.valueOf(table_institucion.getValueAt(filaEditar, 0));
            Connection c = con.conexion();
            try {
                int rtp_usu = JOptionPane.showConfirmDialog(null, "DESEA INACTIVAR EL SELECCIONADO");
                if (rtp_usu == 0) {
                    PreparedStatement update_cli = c.prepareStatement("UPDATE billing_proveedor SET esta_activo=0 where id=?");
                    update_cli.setString(1, id_selec);
                    update_cli.execute();
                    JOptionPane.showMessageDialog(null, "INSTITUCION INACTIVADA CORRECTAMENTE");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                con.desconectar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBE DE SELECCIONAR AL MENOS UN DATO PARA INACTIVAR");
        }
    }//GEN-LAST:event_btn_inst_deleteActionPerformed

    private void btn_inst_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inst_newActionPerformed
        txt_inst_activo.setEnabled(true);
        txt_inst_direcc.setEnabled(true);
        txt_inst_email.setEnabled(true);
        txt_inst_fono.setEnabled(true);
        txt_inst_inactivo.setEnabled(true);
        txt_inst_presidente.setEnabled(true);
        txt_inst_razon.setEnabled(true);
        txt_inst_ruc.setEnabled(true);
        txt_inst_secre.setEnabled(true);
        txt_inst_tesorero.setEnabled(true);
        txt_inst_vice.setEnabled(true);
        btn_inst_save.setEnabled(true);
        hidden_id_modifi_save.setText("0");
        btn_inst_save.setText("Grabar Insituciòn");

    }//GEN-LAST:event_btn_inst_newActionPerformed

    private void btn_inst_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inst_saveActionPerformed
        String inst_id = hidden_id_inst.getText();
        String inst_razon = txt_inst_razon.getText();
        String inst_ruc = txt_inst_ruc.getText();
        String inst_direcc = txt_inst_direcc.getText();
        String inst_email = txt_inst_email.getText();
        String inst_fono = txt_inst_fono.getText();
        String inst_presidente = txt_inst_presidente.getText();
        String inst_vice = txt_inst_vice.getText();
        String inst_secre = txt_inst_secre.getText();
        String inst_tesorero = txt_inst_tesorero.getText();
        Calendar c2 = new GregorianCalendar();
        Date fecha_sis = new Date();
        //Date fecha = 
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String fecha_sys = formato.format(fecha_sis);

        txt_inst_inactivo.setActionCommand("0");
        txt_inst_activo.setActionCommand("1");
        String activo_inactivo = estado_insti.getSelection().getActionCommand();
        String envia_est = null;
        if (activo_inactivo.equals("0")) {
            envia_est = "0";
        }
        if (activo_inactivo.equals("1")) {
            envia_est = "1";
        }
        System.out.println("111112323545");
        try {
            Connection c = con.conexion();
            if (hidden_id_modifi_save.getText().equals("1")) {
                System.out.println("-----------");
                PreparedStatement act = c.prepareStatement("UPDATE billing_proveedor SET PersonaComercio_cedulaRuc=?,razonsocial=?,direccion=?,email=?,telefonos=?,\n"
                        + "presidente=?,vicepresidente=?,secretario=?,tesorero=?,esta_activo=?,fecha=?\n"
                        + "WHERE id=?");
                act.setString(1, inst_ruc);
                act.setString(2, inst_razon);
                act.setString(3, inst_direcc);
                act.setString(4, inst_email);
                act.setString(5, inst_fono);
                act.setString(6, inst_presidente);
                act.setString(7, inst_vice);
                act.setString(8, inst_secre);
                act.setString(9, inst_tesorero);
                act.setString(10, envia_est);
                act.setDate(11, java.sql.Date.valueOf(fecha_sys));
                act.setString(12, inst_id);
                act.execute();

                JOptionPane.showMessageDialog(null, "INSTITUCION MODIFICADA CORRECTAMENTE", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                limpiar_data();
                inactiva();
                list_institucion(inst_razon);
                btn_inst_new.setEnabled(true);

            }

            if (hidden_id_modifi_save.getText().equals("0")) {
                System.out.println("****************");
                PreparedStatement verStmt = c.prepareStatement("SELECT * \n"
                        + "FROM billing_proveedor \n"
                        + "WHERE razonsocial=?");
                verStmt.setString(1, inst_razon);
                ResultSet rs_v = verStmt.executeQuery();

                if (rs_v.last()) {
                    JOptionPane.showMessageDialog(null, "LA INSTITUCION QUE INTENTA AGREGAR YA SE ENCUENTRA REGISTRADA", "VERIFIQUE POR FAVOR", JOptionPane.ERROR_MESSAGE);
                    list_institucion(inst_razon);
                } else {
                    PreparedStatement save = c.prepareStatement("INSERT INTO billing_proveedor (PersonaComercio_cedulaRuc,razonsocial,direccion,email,telefonos,\n"
                            + "presidente,vicepresidente,secretario,tesorero,esta_activo,fecha,es_institucion) \n"
                            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
                    save.setString(1, inst_ruc);
                    save.setString(2, inst_razon);
                    save.setString(3, inst_direcc);
                    save.setString(4, inst_email);
                    save.setString(5, inst_fono);
                    save.setString(6, inst_presidente);
                    save.setString(7, inst_vice);
                    save.setString(8, inst_secre);
                    save.setString(9, inst_tesorero);
                    save.setString(10, envia_est);
                    save.setDate(11, java.sql.Date.valueOf(fecha_sys));
                    save.setString(12, "1");
                    save.execute();

                    JOptionPane.showMessageDialog(null, "INSTITUCION CREADA CORRECTAMENTE", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                    limpiar_data();
                    inactiva();
                    list_institucion(inst_razon);

                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        } finally {
            con.desconectar();
        }

    }//GEN-LAST:event_btn_inst_saveActionPerformed

    public void limpiar_data() {

        txt_inst_razon.setText("");
        txt_inst_ruc.setText("");
        txt_inst_direcc.setText("");
        txt_inst_email.setText("");
        txt_inst_fono.setText("");
        txt_inst_presidente.setText("");
        txt_inst_vice.setText("");
        txt_inst_secre.setText("");
        txt_inst_tesorero.setText("");
        btn_inst_save.setEnabled(false);
        btn_inst_modifica.setEnabled(false);
        btn_inst_delete.setEnabled(false);

    }

    public void inactiva() {

        txt_inst_razon.setEnabled(false);
        txt_inst_ruc.setEnabled(false);
        txt_inst_direcc.setEnabled(false);
        txt_inst_email.setEnabled(false);
        txt_inst_fono.setEnabled(false);
        txt_inst_presidente.setEnabled(false);
        txt_inst_vice.setEnabled(false);
        txt_inst_secre.setEnabled(false);
        txt_inst_tesorero.setEnabled(false);
        txt_inst_inactivo.setEnabled(false);
        txt_inst_activo.setEnabled(false);

    }

    public void activa() {

        txt_inst_razon.setEnabled(true);
        txt_inst_ruc.setEnabled(true);
        txt_inst_direcc.setEnabled(true);
        txt_inst_email.setEnabled(true);
        txt_inst_fono.setEnabled(true);
        txt_inst_presidente.setEnabled(true);
        txt_inst_vice.setEnabled(true);
        txt_inst_secre.setEnabled(true);
        txt_inst_tesorero.setEnabled(true);
        txt_inst_inactivo.setEnabled(true);
        txt_inst_activo.setEnabled(true);

    }

    public void list_institucion(String searchName) {
        Connection c = con.conexion();
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }

        try {
            PreparedStatement pss = null;
            pss = c.prepareStatement("SELECT id,PersonaComercio_cedulaRuc,razonsocial,direccion,email,telefonos,\n"
                    + "presidente,vicepresidente,secretario,tesorero,esta_activo\n"
                    + "FROM billing_proveedor \n"
                    + "WHERE es_institucion =1 AND razonsocial = '" + searchName+"'");

            ResultSet rss = pss.executeQuery();
            while (rss.next()) {
                String act_desc = rss.getString("esta_activo");
                String txt_search = null;
                if (act_desc.equals("1")) {
                    txt_search = "Activo";
                }
                if (act_desc.equals("0")) {
                    txt_search = "Inactivo";
                }
                modeloTabla.addRow(new Object[]{
                    rss.getString("id"),
                    rss.getString("razonsocial"),
                    rss.getString("PersonaComercio_cedulaRuc"),
                    rss.getString("direccion"),
                    rss.getString("email"),
                    rss.getString("telefonos"),
                    rss.getString("presidente"),
                    rss.getString("vicepresidente"),
                    rss.getString("secretario"),
                    rss.getString("tesorero"),
                    txt_search
                });
            }
            this.table_institucion.setModel(modeloTabla);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inst_delete;
    private javax.swing.JButton btn_inst_list;
    private javax.swing.JButton btn_inst_modifica;
    private javax.swing.JButton btn_inst_new;
    private javax.swing.JButton btn_inst_save;
    private javax.swing.ButtonGroup estado_insti;
    private javax.swing.JLabel hidden_id_inst;
    private javax.swing.JLabel hidden_id_modifi_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table_institucion;
    private javax.swing.JRadioButton txt_inst_activo;
    private javax.swing.JTextField txt_inst_direcc;
    private javax.swing.JTextField txt_inst_email;
    private javax.swing.JTextField txt_inst_fono;
    private javax.swing.JRadioButton txt_inst_inactivo;
    private javax.swing.JTextField txt_inst_presidente;
    private javax.swing.JTextField txt_inst_razon;
    private javax.swing.JTextField txt_inst_ruc;
    private javax.swing.JTextField txt_inst_secre;
    private javax.swing.JTextField txt_inst_tesorero;
    private javax.swing.JTextField txt_inst_vice;
    // End of variables declaration//GEN-END:variables
}
