/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.*;
import static views.CuentasCobrar.*;

/**
 *
 * @author Desarrollo
 */
public class addProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form addProducto
     */
    private TableRowSorter trsFiltro;
    conexion_bd con = new conexion_bd();
    DefaultTableModel modeloTabla = new DefaultTableModel();

    public addProducto() {
        initComponents();
        modeloTabla.addColumn("Cod.");
        modeloTabla.addColumn("Cod. Comun");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descrip.");
        modeloTabla.addColumn("pvp(-iva)/pvp(+iva)");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Grupo");
        modeloTabla.addColumn("Estado");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();
        btn_modificar = new javax.swing.JButton();
        btn_inactivar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        search_tabla_comensal = new javax.swing.JTextField();
        search_cbx = new javax.swing.JComboBox();
        grupo_search_product = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btn_search = new javax.swing.JButton();
        txt_search_cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rb_nombre = new javax.swing.JRadioButton();
        rb_codigo = new javax.swing.JRadioButton();
        rb_comun = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btn_modificar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        search_tabla_comensal1 = new javax.swing.JTextField();
        search_cbx1 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADOS DE BUSQUEDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        tabla_clientes.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "COD. COMUN", "PRODUCTO", "DESCRIPCION", "PVP", "MARCA", "MODELO", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tabla_clientes);

        btn_modificar.setBackground(new java.awt.Color(102, 102, 0));
        btn_modificar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("Modificar Producto");

        btn_inactivar.setBackground(new java.awt.Color(204, 0, 0));
        btn_inactivar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_inactivar.setForeground(new java.awt.Color(255, 255, 255));
        btn_inactivar.setText("Inactivar Producto");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel12.setText("Filtrar Busquedas");

        search_tabla_comensal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        search_tabla_comensal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_tabla_comensalKeyTyped(evt);
            }
        });

        search_cbx.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        search_cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Codigo Comun", "Nombre Producto" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_inactivar)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(search_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_tabla_comensal)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_tabla_comensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_inactivar)))
        );

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        btn_search.setBackground(new java.awt.Color(51, 0, 204));
        btn_search.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifier (1).png"))); // NOI18N
        btn_search.setText("Buscar Producto");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_search_cliente.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setText("Eliga la foma de buscar Nombre, Codigo, Cod. Comùn");

        grupo_search_product.add(rb_nombre);
        rb_nombre.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        rb_nombre.setSelected(true);
        rb_nombre.setText("Nombre");
        rb_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nombreActionPerformed(evt);
            }
        });

        grupo_search_product.add(rb_codigo);
        rb_codigo.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        rb_codigo.setText("Codigo");

        grupo_search_product.add(rb_comun);
        rb_comun.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        rb_comun.setText("Cod. Comun");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_search_cliente)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_comun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_codigo)
                .addGap(18, 18, 18)
                .addComponent(btn_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_nombre)
                            .addComponent(rb_codigo)
                            .addComponent(rb_comun)
                            .addComponent(btn_search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADOS DE BUSQUEDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        btn_modificar1.setBackground(new java.awt.Color(102, 102, 0));
        btn_modificar1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_modificar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus-symbol-in-a-rounded-black-square.png"))); // NOI18N
        btn_modificar1.setText("Agregar Producto");
        btn_modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel13.setText("Filtrar Busquedas");

        search_tabla_comensal1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        search_tabla_comensal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_tabla_comensal1KeyTyped(evt);
            }
        });

        search_cbx1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        search_cbx1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Codigo Comun", "Nombre Producto" }));

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla_productos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(search_cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_tabla_comensal1)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 671, Short.MAX_VALUE)
                        .addComponent(btn_modificar1)))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_tabla_comensal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_modificar1)
                .addGap(144, 144, 144))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_nombreActionPerformed

    private void search_tabla_comensalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_tabla_comensalKeyTyped
        search_tabla_comensal.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (search_tabla_comensal.getText());
                search_tabla_comensal.setText(cadena);
                repaint();
                filtro_search();
            }
        });
        trsFiltro = new TableRowSorter(tabla_clientes.getModel());
        tabla_clientes.setRowSorter(trsFiltro);
    }//GEN-LAST:event_search_tabla_comensalKeyTyped

    private void search_tabla_comensal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_tabla_comensal1KeyTyped
        search_tabla_comensal.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (search_tabla_comensal.getText());
                search_tabla_comensal.setText(cadena);
                repaint();
                filtro_search();
            }
        });
        trsFiltro = new TableRowSorter(tabla_clientes.getModel());
        tabla_clientes.setRowSorter(trsFiltro);
    }//GEN-LAST:event_search_tabla_comensal1KeyTyped

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        //btn_modificar.setEnabled(true);

        Connection c = con.conexion();
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }

        try {
            rb_nombre.setActionCommand("0");
            rb_codigo.setActionCommand("1");
            rb_comun.setActionCommand("2");

            String search_cl = grupo_search_product.getSelection().getActionCommand();
            String searchName = txt_search_cliente.getText();
            PreparedStatement pss = null;
            if (search_cl.equals("0")) {
                pss = c.prepareStatement("SELECT p.codigo codp, p.codigo2, p.nombreUnico, p.descripcion, p.estado, m.nombre marca,gp.nombre grupo,	pp.valor pvp\n"
                        + "FROM billing_producto p\n"
                        + "LEFT JOIN producto_precio pp ON p.codigo = pp.id_producto AND pp.id_precio =4\n"
                        + "LEFT JOIN billing_marca m ON p.marca_id = m.id\n"
                        + "LEFT JOIN billing_productogrupo gp ON gp.codigo = p.productogrupo_codigo\n"
                        + "WHERE LOWER(p.nombreUnico)LIKE '%" + searchName + "%' \n"
                        + "OR UPPER(p.nombreUnico)LIKE '%" + searchName + "%'");
            }
            if (search_cl.equals("1")) {
                pss = c.prepareStatement("SELECT p.codigo codp, p.codigo2, p.nombreUnico, p.descripcion, p.estado, m.nombre marca,gp.nombre grupo,pp.valor pvp\n"
                        + "FROM billing_producto p\n"
                        + "LEFT JOIN producto_precio pp ON p.codigo = pp.id_producto AND pp.id_precio =4\n"
                        + "LEFT JOIN billing_marca m ON p.marca_id = m.id\n"
                        + "LEFT JOIN billing_productogrupo gp ON gp.codigo = p.productogrupo_codigo\n"
                        + "WHERE p.codigo = " + searchName);
            }
            if (search_cl.equals("2")) {
                pss = c.prepareStatement("SELECT p.codigo codp, p.codigo2, p.nombreUnico, p.descripcion, p.estado, m.nombre marca,gp.nombre grupo,pp.valor pvp\n"
                        + "FROM billing_producto p\n"
                        + "LEFT JOIN producto_precio pp ON p.codigo = pp.id_producto AND pp.id_precio =4\n"
                        + "LEFT JOIN billing_marca m ON p.marca_id = m.id\n"
                        + "LEFT JOIN billing_productogrupo gp ON gp.codigo = p.productogrupo_codigo\n"
                        + "WHERE LOWER(p.codigo2)LIKE '%" + searchName + "%' \n"
                        + "OR UPPER(p.codigo2)LIKE '%" + searchName + "%'");

            }

            ResultSet rss = pss.executeQuery();
            while (rss.next()) {
                String act_desc = rss.getString("estado");
                String txt_search = null;
                if (act_desc.equals("1")) {
                    txt_search = "Activo";
                }
                if (act_desc.equals("0")) {
                    txt_search = "Inactivo";
                }
                Double pvp_siniva = rss.getDouble("pvp");

                Double val = pvp_siniva * 1.12;
                Double iva = Redondear(val);
                Double siniva = Redondear(pvp_siniva);
                modeloTabla.addRow(new Object[]{
                    rss.getString("codp"),
                    rss.getString("codigo2"),
                    rss.getString("nombreUnico"),
                    rss.getString("descripcion"),
                    siniva + " / " + iva,
                    rss.getString("marca"),
                    rss.getString("grupo"),
                    txt_search

                });
            }

            this.tabla_productos.setModel(modeloTabla);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar1ActionPerformed
        btn_abonar.setEnabled(false);
        valor_producto.setEnabled(true);
        int filaEditar = tabla_productos.getSelectedRow();
        int numfilas = tabla_productos.getSelectedRowCount();
        if (filaEditar >= 0 && numfilas == 1) {

            String codp = String.valueOf(tabla_productos.getValueAt(filaEditar, 0));
            String codigo2 = String.valueOf(tabla_productos.getValueAt(filaEditar, 1));
            String lb_productoa = String.valueOf(tabla_productos.getValueAt(filaEditar, 2));
            String valor_pro = String.valueOf(tabla_productos.getValueAt(filaEditar, 4));

            product_id_hidden.setText(codp);
            txt_abono.setText("0");
            lb_producto.setText(lb_productoa);
            lb_codigo2.setText(codigo2);
            String[] parts = valor_pro.split("/");
            String p_sin_iva = parts[0]; // 123
            String p_con_iva = parts[1];
            pvp_sin_iva.setText(p_sin_iva);
            pvp_con_iva.setText(p_con_iva);
            valor_producto.setText(p_con_iva);
                    
                    
            this.dispose();
            
            btn_search2.setEnabled(true);
            btn_agrega.setEnabled(true);
            txt_abono.setEnabled(true);
            btn_anular_todo.setEnabled(true);
           // btn_anular_pago.setEnabled(true);
            btn_abonar.setEnabled(false);


         
        } else {
            JOptionPane.showMessageDialog(null, "DEBE DE SELECCIONAR AL MENOS UN DATO PARA AGREGAR");
        }
    }//GEN-LAST:event_btn_modificar1ActionPerformed
    public double Redondear(double numero) {
        return Math.rint(numero * 100) / 100;
    }

    public void filtro_search() {

        int columnaAbuscar = 0;
        if (search_cbx.getSelectedItem() == "Nombres") {
            columnaAbuscar = 2;
        }
        if (search_cbx.getSelectedItem() == "Apellidos") {
            columnaAbuscar = 3;
        }

        if (search_cbx.getSelectedItem() == "Cèdula") {
            columnaAbuscar = 1;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + search_tabla_comensal.getText(), columnaAbuscar));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_inactivar;
    public javax.swing.JButton btn_modificar;
    public javax.swing.JButton btn_modificar1;
    public javax.swing.JButton btn_search;
    private javax.swing.ButtonGroup grupo_search_product;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JRadioButton rb_codigo;
    public javax.swing.JRadioButton rb_comun;
    public javax.swing.JRadioButton rb_nombre;
    private javax.swing.JComboBox search_cbx;
    private javax.swing.JComboBox search_cbx1;
    private javax.swing.JTextField search_tabla_comensal;
    private javax.swing.JTextField search_tabla_comensal1;
    public javax.swing.JTable tabla_clientes;
    private javax.swing.JTable tabla_productos;
    public javax.swing.JTextField txt_search_cliente;
    // End of variables declaration//GEN-END:variables
}
