/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;
import static views.PlanAcumulativo.jDateChooser1_ac;

/**
 *
 * @author Desarrollo
 */
public class CuentasCobrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form CuentasCobrar
     */
    conexion_bd con = new conexion_bd();
    DefaultTableModel modeloTabla_cxc = new DefaultTableModel();

    public CuentasCobrar() {
        initComponents();
        btn_search2.setEnabled(false);
        btn_agrega.setEnabled(false);
        btn_abonar.setEnabled(false);
        btn_search2.setEnabled(false);
        btn_anular_todo.setEnabled(false);
        //btn_anular_pago.setEnabled(false);
        Calendar c2 = new GregorianCalendar();
        jDateChooser1.setCalendar(c2);
        valor_producto.setEnabled(false);
        jDateChooser1.setEnabled(false);
        txt_abono.setEnabled(false);

        valor_producto.setEnabled(false);
        modeloTabla_cxc.addColumn("Nro");
        modeloTabla_cxc.addColumn("Fecha");
        modeloTabla_cxc.addColumn("Código");
        modeloTabla_cxc.addColumn("Descripción");
        modeloTabla_cxc.addColumn("Valor");
        modeloTabla_cxc.addColumn("Abono");
        modeloTabla_cxc.addColumn("Saldo");
        modeloTabla_cxc.addColumn("Estado");

        cliente_id_hidden.setVisible(false);
        product_id_hidden.setVisible(false);
        cxc_id_hidden.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_search1 = new javax.swing.JButton();
        txt_names = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        txt_fono_casa = new javax.swing.JTextField();
        txt_fono_trabajo = new javax.swing.JTextField();
        txt_dirc_casa = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_direc_trabajo = new javax.swing.JTextField();
        cliente_id_hidden = new javax.swing.JLabel();
        product_id_hidden = new javax.swing.JLabel();
        cxc_id_hidden = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_agrega = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        valor_producto = new javax.swing.JTextField();
        txt_abono = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_abonar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecxc = new javax.swing.JTable();
        btn_anular_todo = new javax.swing.JButton();
        btn_search5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_observaciones_cc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lb_producto = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lb_codigo2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pvp_sin_iva = new javax.swing.JLabel();
        btn_search2 = new javax.swing.JButton();
        lb_color = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lb_talla = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Nombres y Apellidos");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Celular");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Telf. Cas");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("E-mail");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Direcc.Trab.");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Direcc. Casa");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("Telf. Trabajo");

        btn_search1.setBackground(new java.awt.Color(102, 0, 102));
        btn_search1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search1.setForeground(new java.awt.Color(255, 255, 255));
        btn_search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifier (1).png"))); // NOI18N
        btn_search1.setText("Buscar Cliente");
        btn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search1ActionPerformed(evt);
            }
        });

        txt_names.setEditable(false);
        txt_names.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_celular.setEditable(false);
        txt_celular.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_fono_casa.setEditable(false);
        txt_fono_casa.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_fono_trabajo.setEditable(false);
        txt_fono_trabajo.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_dirc_casa.setEditable(false);
        txt_dirc_casa.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_email.setEditable(false);
        txt_email.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_direc_trabajo.setEditable(false);
        txt_direc_trabajo.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        cliente_id_hidden.setText("cliente_id");

        product_id_hidden.setText("product_id");

        cxc_id_hidden.setText("new_prdt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fono_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fono_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_names))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dirc_casa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_direc_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cliente_id_hidden)
                                .addGap(18, 18, 18)
                                .addComponent(product_id_hidden)
                                .addGap(18, 18, 18)
                                .addComponent(cxc_id_hidden)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(btn_search1)
                    .addGap(16, 16, 16)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fono_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fono_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_dirc_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_direc_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cliente_id_hidden)
                            .addComponent(product_id_hidden)
                            .addComponent(cxc_id_hidden)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(104, Short.MAX_VALUE)
                    .addComponent(btn_search1)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOVAMODA  - CREDITO PERSONAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        btn_agrega.setBackground(new java.awt.Color(0, 102, 255));
        btn_agrega.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_agrega.setForeground(new java.awt.Color(255, 255, 255));
        btn_agrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito-de-la-compra.png"))); // NOI18N
        btn_agrega.setText("Comprar Producto");
        btn_agrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregaActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 204));
        jLabel23.setText("Valor");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 204));
        jLabel24.setText("Abono");

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 204));
        jLabel25.setText("Fecha");

        btn_abonar.setBackground(new java.awt.Color(51, 0, 153));
        btn_abonar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_abonar.setForeground(new java.awt.Color(255, 255, 255));
        btn_abonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallet (1).png"))); // NOI18N
        btn_abonar.setText("Abonar");
        btn_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abonarActionPerformed(evt);
            }
        });

        tablecxc.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tablecxc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FECHA", "CODIGO", "DESCRIPCION", "VALOR", "ABONO", "SALDO"
            }
        ));
        jScrollPane1.setViewportView(tablecxc);

        btn_anular_todo.setBackground(new java.awt.Color(153, 0, 0));
        btn_anular_todo.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_anular_todo.setForeground(new java.awt.Color(255, 255, 255));
        btn_anular_todo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/garbage.png"))); // NOI18N
        btn_anular_todo.setText("Anular CxC");
        btn_anular_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anular_todoActionPerformed(evt);
            }
        });

        btn_search5.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer (1).png"))); // NOI18N
        btn_search5.setText("Imprimir");
        btn_search5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Observaciones:");

        txt_observaciones_cc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(valor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btn_abonar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_observaciones_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_search5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_anular_todo)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(valor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(btn_agrega)
                        .addComponent(btn_abonar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_observaciones_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_anular_todo)
                        .addComponent(btn_search5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Marca");

        lb_producto.setBackground(new java.awt.Color(0, 0, 0));
        lb_producto.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lb_producto.setText("-------------");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 255));
        jLabel17.setText("Cod. Común");

        lb_codigo2.setBackground(new java.awt.Color(0, 0, 0));
        lb_codigo2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lb_codigo2.setText("-------------");

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 102));
        jLabel19.setText("PVP ");

        pvp_sin_iva.setBackground(new java.awt.Color(0, 0, 0));
        pvp_sin_iva.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pvp_sin_iva.setText("-------------");

        btn_search2.setBackground(new java.awt.Color(102, 153, 0));
        btn_search2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search2.setForeground(new java.awt.Color(255, 255, 255));
        btn_search2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifier (1).png"))); // NOI18N
        btn_search2.setText("Datos del Producto");
        btn_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search2ActionPerformed(evt);
            }
        });

        lb_color.setBackground(new java.awt.Color(0, 0, 0));
        lb_color.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lb_color.setText("-------------");

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 102));
        jLabel18.setText("Color");

        lb_talla.setBackground(new java.awt.Color(0, 0, 0));
        lb_talla.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lb_talla.setText("-------------");

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Talla");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_codigo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btn_search2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_talla, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(pvp_sin_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lb_producto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lb_codigo2))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lb_color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pvp_sin_iva)
                    .addComponent(jLabel20)
                    .addComponent(lb_talla))
                .addGap(28, 28, 28)
                .addComponent(btn_search2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search1ActionPerformed
        addCliente newPanel = new addCliente();
        Principal.jDesktopPane1.add(newPanel);
        newPanel.toFront();
        newPanel.setVisible(true);
    }//GEN-LAST:event_btn_search1ActionPerformed

    private void btn_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abonarActionPerformed
        int tipo_transaccion = 2;
        Date fecha = jDateChooser1.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        String abono_s = txt_abono.getText();
        String cliente = cliente_id_hidden.getText();

        Double abono = Double.parseDouble(abono_s);

        try {
            Connection c = con.conexion();
            String id_cxc = cxc_id_hidden.getText();
            PreparedStatement pss = c.prepareStatement("SELECT cc.*, p.nombreUnico, p.codigo2\n"
                    + "FROM bill_cxc_det cc\n"
                    + "LEFT JOIN billing_producto p ON p.codigo = cc.doc_id\n"
                    + "WHERE cc.estado = 1 AND cc.client_id =" + cliente + " AND cc.cxc_id =" + id_cxc + "\n"
                    + "ORDER BY id DESC LIMIT 1");
            ResultSet rss = pss.executeQuery();
            String saldo = null;
            Double saldo_new;
            Double new_saldo = null;
            String fe = formato.format(fecha);
            if (rss.next()) {
                saldo = rss.getString("saldo_client");
                saldo_new = Double.parseDouble(saldo);
                new_saldo = saldo_new - abono;
                PreparedStatement updSaldo = c.prepareStatement("UPDATE bill_cxc_saldos set saldo=?,fecha=? where client_id=?");
                updSaldo.setDouble(1, new_saldo);
                updSaldo.setDate(2, java.sql.Date.valueOf(fe));
                updSaldo.setString(3, cliente);
                updSaldo.execute();
            } else {
                btn_abonar.setEnabled(false);
                /*ACTULIZA EL SALDO*/
                //PreparedStatement updteSaldo = c.prepareStatement("INSERT INTO bill_cxc_saldos(saldo,client_id, fecha)\n"
                //      + "VALUES(?,?,?)");
                PreparedStatement updteSaldo = c.prepareStatement("UPDATE bill_cxc_saldos set saldo=?,fecha=? where client_id=?");
                updteSaldo.setDouble(1, new_saldo);
                updteSaldo.setDate(2, java.sql.Date.valueOf(fe));
                updteSaldo.setString(3, cliente);
                updteSaldo.execute();
                /*-----------------*/
            }

            if (new_saldo < 0) {
                JOptionPane.showMessageDialog(null, "NO SE REALIZAR LA TAREA SALDO QUEDARA EN NEGATIVO");
            } else {

                PreparedStatement s_rol = c.prepareStatement("select id_user from cat_historial_sesiones  order by id desc limit 1");
                ResultSet r_rol = s_rol.executeQuery();
                String cod_user_id = null;
                while (r_rol.next()) {
                    cod_user_id = r_rol.getString("id_user"); // USUARIO ID .. TIPOPAGO ID
                }

                PreparedStatement guardarStmt = c.prepareStatement("INSERT INTO bill_cxc_det(tipotransaccion_cod,cuota_neto, fecha_cobro, client_id, saldo_client,total_neto,tipopago_id,cxc_id)\n"
                        + "VALUES(?,?,?,?,?,?,?,?)");
                guardarStmt.setInt(1, tipo_transaccion);
                guardarStmt.setDouble(2, abono);
                guardarStmt.setDate(3, java.sql.Date.valueOf(fe));
                guardarStmt.setString(4, cliente);
                guardarStmt.setDouble(5, new_saldo);
                guardarStmt.setDouble(6, 0);
                guardarStmt.setString(7, cod_user_id);
                guardarStmt.setString(8, id_cxc);

                guardarStmt.execute();

                if (new_saldo == 0) {
                    PreparedStatement updSaldocc = c.prepareStatement("UPDATE bill_cxc set estado=0, total_neto=? where id=?");
                    updSaldocc.setDouble(1, new_saldo);
                    updSaldocc.setString(2, id_cxc);
                    updSaldocc.execute();
                    cxc_id_hidden.setText("0");
                }

                JOptionPane.showMessageDialog(null, "Abono Registrado Correctamente");
                llena_tabla(cliente);

                lb_producto.setText("");
                lb_codigo2.setText("");
                pvp_sin_iva.setText("");
                // pvp_con_iva.setText("");
                valor_producto.setText("0");
                txt_abono.setText("0");
                btn_agrega.setEnabled(false);
                btn_abonar.setEnabled(true);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }

    }//GEN-LAST:event_btn_abonarActionPerformed

    private void btn_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search2ActionPerformed
        producto_new_cc newPanel = new producto_new_cc();
        Principal.jDesktopPane1.add(newPanel);
        newPanel.toFront();
        newPanel.setVisible(true);
    }//GEN-LAST:event_btn_search2ActionPerformed

    private void btn_agregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregaActionPerformed
        if (txt_observaciones_cc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR LLENE EL CAMPO OBSERVACIONES");
        } else {

            int tipo_transaccion = 1;
            Date fecha = jDateChooser1.getDate();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

            String abono_s = txt_abono.getText();
            String valor_prod = valor_producto.getText();
            String cliente = cliente_id_hidden.getText();
            String cod_prdo = product_id_hidden.getText();

            Double abono = Double.parseDouble(abono_s);
            Double valor_aux = Double.parseDouble(valor_prod);

            try {

                Connection c = con.conexion();
                String cxc_ide = cxc_id_hidden.getText();
                String id_cxc = "999";

                String fe = formato.format(fecha);
                if (cxc_ide.equals("0")) {

                    PreparedStatement newcc = c.prepareStatement("INSERT INTO bill_cxc(fecha_cobro, client_id, total_neto,observaciones)\n"
                            + "VALUES(?,?,?,?)");
                    newcc.setDate(1, java.sql.Date.valueOf(fe));
                    newcc.setString(2, cliente);
                    newcc.setDouble(3, valor_aux);
                    newcc.setString(4, txt_observaciones_cc.getText());
                    newcc.execute();

                    PreparedStatement pscc = c.prepareStatement("SELECT cc.*\n"
                            + "FROM bill_cxc cc\n"
                            + "WHERE cc.estado = 1 AND cc.total_neto > 0 AND cc.client_id =" + cliente + "\n"
                            + "ORDER BY id DESC LIMIT 1");
                    ResultSet rscc = pscc.executeQuery();
                    if (rscc.next()) {
                        id_cxc = rscc.getString("id");
                    }
                } else {

                    id_cxc = cxc_ide;
                }

                PreparedStatement pss = c.prepareStatement("SELECT cc.*, p.nombreUnico, p.codigo2\n"
                        + "FROM bill_cxc_det cc\n"
                        + "LEFT JOIN billing_producto p ON p.codigo = cc.doc_id\n"
                        + "WHERE cc.estado = 1 AND cc.client_id =" + cliente + " AND cc.cxc_id =" + id_cxc + "\n"
                        + "ORDER BY id DESC LIMIT 1");
                ResultSet rss = pss.executeQuery();
                String saldo = null;
                Double saldo_new;
                Double new_saldo = null;
                Double aux_new = null;

                if (rss.next()) {
                    saldo = rss.getString("saldo_client");
                    saldo_new = Double.parseDouble(saldo);
                    new_saldo = (saldo_new + valor_aux) - abono;

                    PreparedStatement updSaldo = c.prepareStatement("UPDATE bill_cxc_saldos set saldo=?,fecha=? where client_id=?");
                    updSaldo.setDouble(1, new_saldo);
                    updSaldo.setDate(2, java.sql.Date.valueOf(fe));
                    updSaldo.setString(3, cliente);
                    updSaldo.execute();

                } else {

                    new_saldo = valor_aux;
                    PreparedStatement ca = c.prepareStatement("SELECT cc.*\n"
                            + "FROM bill_cxc_saldos cc\n"
                            + "WHERE cc.client_id =" + cliente);
                    ResultSet ra = ca.executeQuery();
                    int encontro = 0;
                    if (ra.next()) {
                        encontro = ra.getInt("id");
                    }

                    if (encontro == 0) {
                        PreparedStatement updteSaldo = c.prepareStatement("INSERT INTO bill_cxc_saldos(saldo,fecha,client_id)\n"
                                + "VALUES(?,?,?)");
                        //PreparedStatement updteSaldo = c.prepareStatement("UPDATE bill_cxc_saldos set saldo=?,fecha=? where client_id=?");
                        updteSaldo.setDouble(1, new_saldo);
                        updteSaldo.setDate(2, java.sql.Date.valueOf(fe));
                        updteSaldo.setString(3, cliente);
                        updteSaldo.execute();
                    } else {
                        //  PreparedStatement updteSaldo = c.prepareStatement("INSERT INTO bill_cxc_saldos(saldo,fecha,client_id)\n"
                        //   + "VALUES(?,?,?)");
                        PreparedStatement updteSaldo = c.prepareStatement("UPDATE bill_cxc_saldos set saldo=?,fecha=? where client_id=?");
                        updteSaldo.setDouble(1, new_saldo);
                        updteSaldo.setDate(2, java.sql.Date.valueOf(fe));
                        updteSaldo.setString(3, cliente);
                        updteSaldo.execute();
                    }
                }

                if (new_saldo < 0) {
                    JOptionPane.showMessageDialog(null, "NO SE REALIZO EL PROCESO\n EL SALDO QUEDARA EN NEGATIVO");
                } else {
                    /* PreparedStatement pcc = c.prepareStatement("SELECT cc.*\n"
                        + "FROM bill_cxc cc\n"
                        + "WHERE cc.estado = 1 AND cc.total_neto > 0 AND cc.client_id =" + cliente + "\n"
                        + "ORDER BY id DESC LIMIT 1");
                ResultSet rcc = pcc.executeQuery();
                if (rcc.next()) {
                    id_cxc = rcc.getString("id");
                }*/
                    cxc_id_hidden.setText(id_cxc);

                    PreparedStatement s_rol = c.prepareStatement("select id_user from cat_historial_sesiones  order by id desc limit 1");
                    ResultSet r_rol = s_rol.executeQuery();
                    String cod_user_id = null;
                    while (r_rol.next()) {
                        cod_user_id = r_rol.getString("id_user"); // USUARIO ID .. TIPOPAGO ID
                    }

                    PreparedStatement guardarStmt = c.prepareStatement("INSERT INTO bill_cxc_det(tipotransaccion_cod,cuota_neto, fecha_cobro, client_id, saldo_client,total_neto, doc_id, tipopago_id, cxc_id)\n"
                            + "VALUES(?,?,?,?,?,?,?,?,?)");
                    guardarStmt.setInt(1, tipo_transaccion);
                    guardarStmt.setDouble(2, abono);
                    guardarStmt.setDate(3, java.sql.Date.valueOf(fe));
                    guardarStmt.setString(4, cliente);
                    guardarStmt.setDouble(5, new_saldo);
                    guardarStmt.setDouble(6, valor_aux);
                    guardarStmt.setString(7, cod_prdo);
                    guardarStmt.setString(8, cod_user_id);
                    guardarStmt.setString(9, id_cxc);

                    guardarStmt.execute();

                    JOptionPane.showMessageDialog(null, "Producto Registrado Correctamente");
                    llena_tabla(cliente);

                    lb_producto.setText("-------");
                    lb_codigo2.setText("-------");
                    pvp_sin_iva.setText("-------");
                    //pvp_con_iva.setText("-------");
                    valor_producto.setEnabled(false);
                    valor_producto.setText("0");
                    txt_observaciones_cc.setText("");
                    txt_abono.setText("0");
                    btn_agrega.setEnabled(false);
                    btn_abonar.setEnabled(true);
                }

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                con.desconectar();
            }
        }
    }//GEN-LAST:event_btn_agregaActionPerformed

    private void btn_search5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search5ActionPerformed
        int i = 0;
        String datos = "";
        List result = new ArrayList();
        model_cxc_ac list_cxc;
        result.clear();
        try {
            for (i = 0; i < tablecxc.getRowCount(); i++) {
                String nro = String.valueOf(tablecxc.getValueAt(i, 0));
                String fecha = String.valueOf(tablecxc.getValueAt(i, 1));
                String codigo = String.valueOf(tablecxc.getValueAt(i, 2));
                String descripcion = String.valueOf(tablecxc.getValueAt(i, 3));
                String valor = String.valueOf(tablecxc.getValueAt(i, 4));
                String abono = String.valueOf(tablecxc.getValueAt(i, 5));
                String saldo = String.valueOf(tablecxc.getValueAt(i, 6));
                //String estado = String.valueOf(tablecxc.getValueAt(i, 7));
                list_cxc = new model_cxc_ac(nro, fecha, codigo, descripcion, valor, abono, saldo);
                result.add(list_cxc);

            }
            Map map = new HashMap();

            JasperPrint jPrint;
            JDialog report = new JDialog();
            report.setSize(900, 700);
            report.setLocationRelativeTo(null);
            report.setTitle("CXC");
            String client = txt_names.getText();
            String dir = txt_dirc_casa.getText();
            String tlf = txt_celular.getText();
            String obser = txt_observaciones_cc.getText();

            map.put("titulo", "COMPROBANTE DE CREDITO PERSONAL - CALZADO NOVAMODA");
            map.put("cliente", client);
            map.put("direccion", dir);
            map.put("celular", tlf);
            map.put("observacion", obser);

            jPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reports/cxc.jasper"), map, new JRBeanCollectionDataSource(result));
            JRViewer jv = new JRViewer(jPrint);
            report.getContentPane().add(jv);
            report.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(views_informecxc.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*try {
            MessageFormat headerFormat = new MessageFormat("Registro de Saldos");
            MessageFormat fooderFormat = new MessageFormat("Registro de Saldos");
            tablecxc.print(JTable.PrintMode.FIT_WIDTH, headerFormat, fooderFormat);
        } catch (Exception e) {
            Logger.getLogger(CuentasCobrar.class.getName()).log(Level.SEVERE, null, e);
        }*/
    }//GEN-LAST:event_btn_search5ActionPerformed

    private void btn_anular_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anular_todoActionPerformed
        String cxc_id = cxc_id_hidden.getText();
        int n = JOptionPane.showConfirmDialog(
                null, "Esta seguro de eliminar todo la CxC?",
                "Eliga una opcion",
                JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.out.println("siii");
            try {

                Connection c = con.conexion();

                PreparedStatement psos = c.prepareStatement("SELECT *\n"
                        + "FROM bill_cxc \n"
                        + "WHERE  id =? ");
                psos.setString(1, cxc_id);
                ResultSet rsos = psos.executeQuery();
                String cedula = "";
                while (rsos.next()) {
                    cedula = rsos.getString("client_id");
                }

                /*ACTULIZA PRIMERO LA TABLA CXC*/
                PreparedStatement upt_cxc = c.prepareStatement("UPDATE bill_cxc set estado=0 WHERE id=?");
                upt_cxc.setString(1, cxc_id);
                upt_cxc.execute();

                /*--------*/
 /*ACTULIZA PRIMERO LA TABLA CXC_SALDO*/
                PreparedStatement upt_cxc_sl = c.prepareStatement("UPDATE bill_cxc_saldos set saldo=0 WHERE client_id=?");
                upt_cxc_sl.setString(1, cedula);
                upt_cxc_sl.execute();

                /*--------*/
 /*ACTULIZA PRIMERO LA TABLA CXC_DET*/
                PreparedStatement upt_cxc_det = c.prepareStatement("UPDATE bill_cxc_det set estado=0 WHERE cxc_id=?");
                upt_cxc_det.setString(1, cxc_id);
                upt_cxc_det.execute();

                /*--------*/
                llena_tabla(cedula);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                con.desconectar();
            }
        } else if (n == JOptionPane.NO_OPTION) {
            System.out.println("noo");
        }
    }//GEN-LAST:event_btn_anular_todoActionPerformed
    public void limpiar_campor() {
        lb_producto.setText("");
        lb_codigo2.setText("");
        pvp_sin_iva.setText("");
        // pvp_con_iva.setText("");
        valor_producto.setText("0");
        txt_abono.setText("0");
        btn_agrega.setEnabled(true);
        btn_abonar.setEnabled(false);

    }

    public void llena_tabla(String cedula_selec) {
        while (modeloTabla_cxc.getRowCount() > 0) {
            modeloTabla_cxc.removeRow(0);
        }
        try {
            Connection c = con.conexion();
            PreparedStatement ps = c.prepareStatement("SELECT cc.*\n"
                    + "FROM bill_cxc_det cc\n"
                    + "WHERE cc.estado = 1 AND cc.saldo_client =0 AND cc.client_id =" + cedula_selec + "\n"
                    + "ORDER BY id DESC LIMIT 1");
            ResultSet rs = ps.executeQuery();
            int id_ultimo = 0;
            if (rs.next()) {
                id_ultimo = rs.getInt("id");
            }

            PreparedStatement pss = c.prepareStatement("SELECT cc.*, p.nombreUnico, p.codigo2\n"
                    + "FROM bill_cxc_det cc\n"
                    + "LEFT JOIN billing_producto p ON p.codigo = cc.doc_id\n"
                    + "LEFT JOIN bill_cxc_saldos ps ON ps.client_id = cc.client_id\n"
                    + "WHERE ps.saldo > 0 AND cc.estado = 1 AND cc.client_id =" + cedula_selec + "\n"
                    + "AND cc.id >" + id_ultimo);
            ResultSet rss = pss.executeQuery();
            String est = null;
            while (rss.next()) {
                Double saldo_estado = rss.getDouble("saldo_client");
                if (saldo_estado == 0) {
                    est = "CANCELADO";

                } else {
                    est = "ADEUDA";

                }
                String cdo = rss.getString("codigo2");
                String aux_cdo = null;
                System.out.println("--> " + cdo);
                if (cdo == null) {
                    aux_cdo = "-";
                } else {
                    aux_cdo = cdo;
                }

                String nunico = rss.getString("nombreUnico");
                String aux_nunico = null;

                if (nunico == null) {
                    aux_nunico = "-";
                } else {
                    aux_nunico = nunico;
                }
                modeloTabla_cxc.addRow(new Object[]{
                    rss.getString("id"),
                    rss.getString("fecha_cobro"),
                    aux_cdo,
                    aux_nunico,
                    rss.getString("total_neto"),
                    rss.getString("cuota_neto"),
                    rss.getString("saldo_client"),
                    est,});
            }

            tablecxc.setModel(modeloTabla_cxc);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_abonar;
    public static javax.swing.JButton btn_agrega;
    public static javax.swing.JButton btn_anular_todo;
    public javax.swing.JButton btn_search1;
    public static javax.swing.JButton btn_search2;
    public javax.swing.JButton btn_search5;
    public static javax.swing.JLabel cliente_id_hidden;
    public static javax.swing.JLabel cxc_id_hidden;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lb_codigo2;
    public static javax.swing.JLabel lb_color;
    public static javax.swing.JLabel lb_producto;
    public static javax.swing.JLabel lb_talla;
    public static javax.swing.JLabel product_id_hidden;
    public static javax.swing.JLabel pvp_sin_iva;
    public static javax.swing.JTable tablecxc;
    public static javax.swing.JTextField txt_abono;
    public static javax.swing.JTextField txt_celular;
    public static javax.swing.JTextField txt_dirc_casa;
    public static javax.swing.JTextField txt_direc_trabajo;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_fono_casa;
    public static javax.swing.JTextField txt_fono_trabajo;
    public static javax.swing.JTextField txt_names;
    public static javax.swing.JTextField txt_observaciones_cc;
    public static javax.swing.JTextField valor_producto;
    // End of variables declaration//GEN-END:variables
}
