/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.conexion_bd;

/**
 *
 * @author Desarrollo
 */
public class PlanAcumulativo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CuentasCobrar
     */
    conexion_bd con = new conexion_bd();
    DefaultTableModel modeloTabla_cxc = new DefaultTableModel();

    public PlanAcumulativo() {
        initComponents();
        btn_search2.setEnabled(false);
        btn_agrega.setEnabled(false);
        btn_abonar.setEnabled(false);
        btn_search2.setEnabled(false);
        btn_modificar_reg.setEnabled(false);
        btn_anular_pago.setEnabled(false);
        txt_nro_funda.setEnabled(false);

        valor_producto.setEnabled(false);
        jDateChooser1_ac.setEnabled(false);
        txt_abono.setEnabled(false);

        valor_producto.setEnabled(false);
        modeloTabla_cxc.addColumn("Nro");
        modeloTabla_cxc.addColumn("Fecha");
        modeloTabla_cxc.addColumn("Codigo");
        modeloTabla_cxc.addColumn("Descripcion");
        modeloTabla_cxc.addColumn("Valor");
        modeloTabla_cxc.addColumn("Abono");
        modeloTabla_cxc.addColumn("Saldo");
        modeloTabla_cxc.addColumn("Estado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecxc_ac = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_search1 = new javax.swing.JButton();
        txt_names_ac = new javax.swing.JTextField();
        txt_celular_ac = new javax.swing.JTextField();
        txt_fono_casa_ac = new javax.swing.JTextField();
        txt_fono_trabajo_ac = new javax.swing.JTextField();
        txt_dirc_casa_ac = new javax.swing.JTextField();
        txt_email_ac = new javax.swing.JTextField();
        txt_direc_trabajo_ac = new javax.swing.JTextField();
        cliente_id_hidden_ac = new javax.swing.JLabel();
        product_id_hidden_ac = new javax.swing.JLabel();
        cxc_id_hidden_ac = new javax.swing.JLabel();
        funda_id_hidden_ac = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_agrega = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        valor_producto = new javax.swing.JTextField();
        txt_abono = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_abonar = new javax.swing.JButton();
        jDateChooser1_ac = new com.toedter.calendar.JDateChooser();
        txt_nro_funda = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lb_producto = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lb_codigo2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pvp_sin_iva = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pvp_con_iva = new javax.swing.JLabel();
        btn_search2 = new javax.swing.JButton();
        btn_modificar_reg = new javax.swing.JButton();
        btn_anular_pago = new javax.swing.JButton();
        btn_search5 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tablecxc_ac.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tablecxc_ac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FECHA", "CODIGO", "DESCRIPCION", "VALOR", "ABONO", "SALDO"
            }
        ));
        jScrollPane1.setViewportView(tablecxc_ac);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Nombres y Apellidos");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Celular");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Tlf. Cas");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("E-mail");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Direcc.Trab.");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Dirc. Casa");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("Tlf. Trabajo");

        btn_search1.setBackground(new java.awt.Color(102, 0, 102));
        btn_search1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search1.setForeground(new java.awt.Color(255, 255, 255));
        btn_search1.setText("Buscar Cliente");
        btn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search1ActionPerformed(evt);
            }
        });

        txt_names_ac.setEditable(false);
        txt_names_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_celular_ac.setEditable(false);
        txt_celular_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_fono_casa_ac.setEditable(false);
        txt_fono_casa_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_fono_trabajo_ac.setEditable(false);
        txt_fono_trabajo_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_dirc_casa_ac.setEditable(false);
        txt_dirc_casa_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_email_ac.setEditable(false);
        txt_email_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        txt_direc_trabajo_ac.setEditable(false);
        txt_direc_trabajo_ac.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        cliente_id_hidden_ac.setText("cliente_id");

        product_id_hidden_ac.setText("product_id");

        cxc_id_hidden_ac.setText("new_prdt");

        funda_id_hidden_ac.setText("id_funda_hidden");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_celular_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fono_casa_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fono_trabajo_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_names_ac))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dirc_casa_ac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_direc_trabajo_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_email_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cliente_id_hidden_ac)
                                .addGap(18, 18, 18)
                                .addComponent(product_id_hidden_ac)
                                .addGap(18, 18, 18)
                                .addComponent(cxc_id_hidden_ac)
                                .addGap(29, 29, 29)
                                .addComponent(funda_id_hidden_ac)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(btn_search1)
                    .addGap(16, 16, 16)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_names_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txt_celular_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fono_casa_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fono_trabajo_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_dirc_casa_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_direc_trabajo_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cliente_id_hidden_ac)
                            .addComponent(product_id_hidden_ac)
                            .addComponent(cxc_id_hidden_ac)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_email_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funda_id_hidden_ac)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(104, Short.MAX_VALUE)
                    .addComponent(btn_search1)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOVAMODA  - PLAN ACUMULATIVO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 102, 0))); // NOI18N

        btn_agrega.setBackground(new java.awt.Color(0, 102, 255));
        btn_agrega.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_agrega.setForeground(new java.awt.Color(255, 255, 255));
        btn_agrega.setText("Agregar Producto");
        btn_agrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregaActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 204));
        jLabel23.setText("Valor");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 204));
        jLabel24.setText("Abono");

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 204));
        jLabel25.setText("Fecha");

        btn_abonar.setBackground(new java.awt.Color(51, 0, 153));
        btn_abonar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_abonar.setForeground(new java.awt.Color(255, 255, 255));
        btn_abonar.setText("Abonar");
        btn_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abonarActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 204));
        jLabel26.setText("Nro Funda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(valor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nro_funda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_agrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_abonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agrega)
                    .addComponent(jLabel23)
                    .addComponent(valor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(txt_nro_funda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_abonar))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1_ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 102, 0))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Nombre Prod.");

        lb_producto.setBackground(new java.awt.Color(0, 0, 0));
        lb_producto.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lb_producto.setText("-------------");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Codigo");

        lb_codigo2.setBackground(new java.awt.Color(0, 0, 0));
        lb_codigo2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lb_codigo2.setText("-------------");

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("PVP (-iva)");

        pvp_sin_iva.setBackground(new java.awt.Color(0, 0, 0));
        pvp_sin_iva.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pvp_sin_iva.setText("-------------");

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 204));
        jLabel21.setText("PVP (+iva)");

        pvp_con_iva.setBackground(new java.awt.Color(0, 0, 0));
        pvp_con_iva.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pvp_con_iva.setText("-------------");

        btn_search2.setBackground(new java.awt.Color(102, 153, 0));
        btn_search2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search2.setForeground(new java.awt.Color(255, 255, 255));
        btn_search2.setText("Buscar Producto");
        btn_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_codigo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(btn_search2))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(pvp_con_iva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(pvp_sin_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lb_producto))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lb_codigo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pvp_sin_iva))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(pvp_con_iva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_search2)
                .addContainerGap())
        );

        btn_modificar_reg.setBackground(new java.awt.Color(204, 204, 0));
        btn_modificar_reg.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_modificar_reg.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar_reg.setText("Modificar");

        btn_anular_pago.setBackground(new java.awt.Color(102, 0, 0));
        btn_anular_pago.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_anular_pago.setForeground(new java.awt.Color(255, 255, 255));
        btn_anular_pago.setText("Anular");
        btn_anular_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anular_pagoActionPerformed(evt);
            }
        });

        btn_search5.setBackground(new java.awt.Color(102, 102, 102));
        btn_search5.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_search5.setForeground(new java.awt.Color(0, 0, 102));
        btn_search5.setText("Imprimir");
        btn_search5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_search5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modificar_reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_anular_pago))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar_reg)
                    .addComponent(btn_anular_pago)
                    .addComponent(btn_search5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search1ActionPerformed
        addCliente_ac newPanel = new addCliente_ac();
        Principal.jDesktopPane1.add(newPanel);
        newPanel.toFront();
        newPanel.setVisible(true);
    }//GEN-LAST:event_btn_search1ActionPerformed

    private void btn_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abonarActionPerformed
        int tipo_transaccion = 2;
        Date fecha = jDateChooser1_ac.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        String abono_s = txt_abono.getText();
        String cliente = cliente_id_hidden_ac.getText();

        Double abono = Double.parseDouble(abono_s);

        try {
            Connection c = con.conexion();
            PreparedStatement pss = c.prepareStatement("SELECT cc.*, p.nombreUnico, p.codigo2\n"
                    + "FROM bill_cxc_ac cc\n"
                    + "LEFT JOIN billing_producto p ON p.codigo = cc.doc_id\n"
                    + "WHERE cc.estado = 1 AND cc.client_id =" + cliente + "\n"
                    + "ORDER BY id DESC LIMIT 1");
            ResultSet rss = pss.executeQuery();
            String saldo = null;
            Double saldo_new;
            Double new_saldo = null;
            String fe = formato.format(fecha);
            if (rss.next()) {
                saldo = rss.getString("saldo_client");
                saldo_new = Double.parseDouble(saldo);
                new_saldo = saldo_new - abono;
                PreparedStatement updSaldo = c.prepareStatement("UPDATE bill_cxc_saldos_ac set saldo=?,fecha=? where client_id=?");
                updSaldo.setDouble(1, new_saldo);
                updSaldo.setDate(2, java.sql.Date.valueOf(fe));
                updSaldo.setString(3, cliente);
                updSaldo.execute();

                if (new_saldo == 0) {
                    int num_fun_new = 0;
                    String f_new = txt_nro_funda.getText();
                    num_fun_new = Integer.parseInt(f_new);

                    PreparedStatement updfunda = c.prepareStatement("UPDATE bill_funda_acumulativo set estado_funda=0, num_funda=?,cliente_dni=?  where num_funda=?");
                    updfunda.setInt(1, num_fun_new);
                    updfunda.setString(2, cliente);
                    updfunda.setInt(3, num_fun_new);
                    updfunda.execute();

                    PreparedStatement ps_acc = c.prepareStatement("SELECT ac.*\n"
                            + "FROM bill_funda_acumulativo ac\n"
                            //+ "WHERE ac.estado_funda = 1\n"
                            + "ORDER BY num_funda DESC LIMIT 1");
                    ResultSet rs_acc = ps_acc.executeQuery();
                    int id_funda_n = 0;
                    while (rs_acc.next()) {
                        id_funda_n = rs_acc.getInt("num_funda");
                    }

                    if (id_funda_n == 0) {
                        txt_nro_funda.setText("1");
                    } else {
                        PreparedStatement ps_ac = c.prepareStatement("SELECT ac.*\n"
                                + "FROM bill_funda_acumulativo ac\n"
                                + "WHERE ac.estado_funda = 1 AND ac.cliente_dni=? \n"
                                + "ORDER BY num_funda DESC LIMIT 1");
                        ps_ac.setString(1, cliente);
                        ResultSet rs_ac = ps_ac.executeQuery();
                        int id_funda = 0;
                        while (rs_ac.next()) {
                            id_funda = rs_ac.getInt("num_funda");
                        }
                        int new_fun = 0;
                        if (id_funda == 0) {
                            new_fun = id_funda_n + 1;
                            txt_nro_funda.setText(String.valueOf(new_fun));
                        } else {
                            txt_nro_funda.setText(String.valueOf(id_funda));
                            //id_funda_n
                        }
                    }
                }

            } else {
                btn_abonar.setEnabled(false);
                /*ACTULIZA EL SALDO*/
                PreparedStatement updteSaldo = c.prepareStatement("INSERT INTO bill_cxc_saldos_ac(saldo,client_id, fecha)\n"
                        + "VALUES(?,?,?)");
                updteSaldo.setDouble(1, new_saldo);
                updteSaldo.setString(2, cliente);
                updteSaldo.setDate(3, java.sql.Date.valueOf(fe));
                updteSaldo.execute();
                /*-----------------*/
            }

            if (new_saldo < 0) {
                JOptionPane.showMessageDialog(null, "NO SE REALIZAR LA TAREA SALDO QUEDARA EN NEGATIVO");
            } else {
                
                PreparedStatement s_rol = c.prepareStatement("select id_user from cat_historial_sesiones  order by id desc limit 1");
                ResultSet r_rol = s_rol.executeQuery();
                String cod_user_id = null;
                while (r_rol.next()) {
                    cod_user_id = r_rol.getString("id_user"); // USUARIO ID .. TIPOPAGO ID
                }
                
                PreparedStatement guardarStmt = c.prepareStatement("INSERT INTO bill_cxc_ac(tipotransaccion_cod,cuota_neto, fecha_cobro, client_id, saldo_client,total_neto,tipopago_id)\n"
                        + "VALUES(?,?,?,?,?,?,?)");
                guardarStmt.setInt(1, tipo_transaccion);
                guardarStmt.setDouble(2, abono);
                guardarStmt.setDate(3, java.sql.Date.valueOf(fe));
                guardarStmt.setString(4, cliente);
                guardarStmt.setDouble(5, new_saldo);
                guardarStmt.setDouble(6, 0);
                guardarStmt.setString(7, cod_user_id);

                guardarStmt.execute();
                JOptionPane.showMessageDialog(null, "Abono Registrado Correctamente");
                llena_tabla(cliente);

                lb_producto.setText("");
                lb_codigo2.setText("");
                pvp_sin_iva.setText("");
                pvp_con_iva.setText("");
                valor_producto.setText("0");
                txt_abono.setText("0");
                btn_agrega.setEnabled(false);
                btn_abonar.setEnabled(true);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }

    }//GEN-LAST:event_btn_abonarActionPerformed

    private void btn_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search2ActionPerformed
        addProducto_ac newPanel = new addProducto_ac();
        Principal.jDesktopPane1.add(newPanel);
        newPanel.toFront();
        newPanel.setVisible(true);
    }//GEN-LAST:event_btn_search2ActionPerformed

    private void btn_agregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregaActionPerformed
        int tipo_transaccion = 1;
        Date fecha = jDateChooser1_ac.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        String abono_s = txt_abono.getText();
        String valor_prod = valor_producto.getText();
        String cliente = cliente_id_hidden_ac.getText();
        String cod_prdo = product_id_hidden_ac.getText();

        Double abono = Double.parseDouble(abono_s);
        Double valor_aux = Double.parseDouble(valor_prod);

        try {

            Connection c = con.conexion();
            PreparedStatement pss = c.prepareStatement("SELECT cc.*, p.nombreUnico, p.codigo2\n"
                    + "FROM bill_cxc_ac cc\n"
                    + "LEFT JOIN billing_producto p ON p.codigo = cc.doc_id\n"
                    + "WHERE cc.estado = 1 AND cc.client_id =" + cliente + "\n"
                    + "ORDER BY id DESC LIMIT 1");
            ResultSet rss = pss.executeQuery();
            String saldo = null;
            Double saldo_new;
            Double new_saldo = null;
            Double aux_new = null;
            String fe = formato.format(fecha);

            if (rss.next()) {
                saldo = rss.getString("saldo_client");
                saldo_new = Double.parseDouble(saldo);
                new_saldo = (saldo_new + valor_aux) - abono;

                PreparedStatement updSaldo = c.prepareStatement("UPDATE bill_cxc_saldos_ac set saldo=?,fecha=? where client_id=?");
                updSaldo.setDouble(1, new_saldo);
                updSaldo.setDate(2, java.sql.Date.valueOf(fe));
                updSaldo.setString(3, cliente);
                updSaldo.execute();

            } else {

                new_saldo = valor_aux;
                /*ACTULIZA EL SALDO*/
                PreparedStatement updteSaldo = c.prepareStatement("INSERT INTO bill_cxc_saldos_ac(saldo,client_id, fecha)\n"
                        + "VALUES(?,?,?)");
                updteSaldo.setDouble(1, new_saldo);
                updteSaldo.setString(2, cliente);
                updteSaldo.setDate(3, java.sql.Date.valueOf(fe));
                updteSaldo.execute();
                /*-----------------*/
            }

            if (new_saldo < 0) {
                JOptionPane.showMessageDialog(null, "NO SE REALIZO EL PROCESO\n EL SALDO QUEDARA EN NEGATIVO");
            } else {
                
                PreparedStatement s_rol = c.prepareStatement("select id_user from cat_historial_sesiones  order by id desc limit 1");
                ResultSet r_rol = s_rol.executeQuery();
                String cod_user_id = null;
                while (r_rol.next()) {
                    cod_user_id = r_rol.getString("id_user"); // USUARIO ID .. TIPOPAGO ID
                }
            
                PreparedStatement guardarStmt = c.prepareStatement("INSERT INTO bill_cxc_ac(tipotransaccion_cod,cuota_neto, fecha_cobro, client_id, saldo_client,total_neto, doc_id, tipopago_id)\n"
                        + "VALUES(?,?,?,?,?,?,?,?)");
                guardarStmt.setInt(1, tipo_transaccion);
                guardarStmt.setDouble(2, abono);
                guardarStmt.setDate(3, java.sql.Date.valueOf(fe));
                guardarStmt.setString(4, cliente);
                guardarStmt.setDouble(5, new_saldo);
                guardarStmt.setDouble(6, valor_aux);
                guardarStmt.setString(7, cod_prdo);
                guardarStmt.setString(8, cod_user_id);
                guardarStmt.execute();

                /*GUARDA EL NUMERO DE FUNDA*/
                int num_fun_new = 0;
                String f_new = txt_nro_funda.getText();
                num_fun_new = Integer.parseInt(f_new);

                PreparedStatement psos = c.prepareStatement("SELECT *\n"
                        + "FROM bill_funda_acumulativo \n"
                        + "WHERE  cliente_dni =? AND num_funda =?");

                psos.setString(1, cliente);
                psos.setInt(2, num_fun_new);

                ResultSet rsos = psos.executeQuery();
                if (rsos.next()) {
                    System.out.println("actuliza");
                    PreparedStatement updfunda = c.prepareStatement("UPDATE bill_funda_acumulativo set num_funda=?,cliente_dni=? where num_funda=?");
                    updfunda.setInt(1, num_fun_new);
                    updfunda.setString(2, cliente);
                    updfunda.setInt(3, num_fun_new);
                    updfunda.execute();

                } else {
                    System.out.println("nuevo");
                    PreparedStatement guardarStmt_fun = c.prepareStatement("INSERT INTO bill_funda_acumulativo(num_funda, cliente_dni)\n"
                            + "VALUES(?,?)");
                    guardarStmt_fun.setInt(1, num_fun_new);
                    guardarStmt_fun.setString(2, cliente);

                    guardarStmt_fun.execute();

                }

                /*--------------------*/
                JOptionPane.showMessageDialog(null, "Producto Registrado Correctamente");
                llena_tabla(cliente);

                lb_producto.setText("-------");
                lb_codigo2.setText("-------");
                pvp_sin_iva.setText("-------");
                pvp_con_iva.setText("-------");
                valor_producto.setEnabled(false);
                valor_producto.setText("0");
                txt_abono.setText("0");
                btn_agrega.setEnabled(false);
                btn_abonar.setEnabled(true);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }
    }//GEN-LAST:event_btn_agregaActionPerformed

    private void btn_search5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search5ActionPerformed
        try {
            MessageFormat headerFormat = new MessageFormat("Registro de Saldos");
            MessageFormat fooderFormat = new MessageFormat("Registro de Saldos");
            tablecxc_ac.print(JTable.PrintMode.FIT_WIDTH, headerFormat, fooderFormat);
        } catch (Exception e) {
            Logger.getLogger(PlanAcumulativo.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_search5ActionPerformed

    private void btn_anular_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anular_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anular_pagoActionPerformed
    public void limpiar_campor() {
        lb_producto.setText("");
        lb_codigo2.setText("");
        pvp_sin_iva.setText("");
        pvp_con_iva.setText("");
        valor_producto.setText("0");
        txt_abono.setText("0");
        btn_agrega.setEnabled(true);
        btn_abonar.setEnabled(false);

    }

    public void llena_tabla(String cedula_selec) {
        while (modeloTabla_cxc.getRowCount() > 0) {
            modeloTabla_cxc.removeRow(0);
        }
        try {
            Connection c = con.conexion();
            PreparedStatement ps = c.prepareStatement("SELECT cc.*\n"
                    + "FROM bill_cxc_ac cc\n"
                    + "WHERE cc.estado = 1 AND cc.saldo_client =0 AND cc.client_id =" + cedula_selec + "\n"
                    + "ORDER BY id DESC LIMIT 1");
            ResultSet rs = ps.executeQuery();
            int id_ultimo = 0;
            if (rs.next()) {
                id_ultimo = rs.getInt("id");
            }

            PreparedStatement pss = c.prepareStatement("SELECT cc.*, p.nombreUnico, p.codigo2\n"
                    + "FROM bill_cxc_ac cc\n"
                    + "LEFT JOIN billing_producto p ON p.codigo = cc.doc_id\n"
                    + "LEFT JOIN bill_cxc_saldos_ac ps ON ps.client_id = cc.client_id\n"
                    + "WHERE ps.saldo > 0 AND cc.estado = 1 AND cc.client_id =" + cedula_selec + "\n"
                    + "AND cc.id >" + id_ultimo);
            ResultSet rss = pss.executeQuery();
            String est = null;
            while (rss.next()) {
                Double saldo_estado = rss.getDouble("saldo_client");
                if (saldo_estado == 0) {
                    est = "CANCELADO";

                } else {
                    est = "ADEUDA";

                }
                modeloTabla_cxc.addRow(new Object[]{
                    rss.getString("id"),
                    rss.getString("fecha_cobro"),
                    rss.getString("codigo2"),
                    rss.getString("nombreUnico"),
                    rss.getString("total_neto"),
                    rss.getString("cuota_neto"),
                    rss.getString("saldo_client"),
                    est,});
            }

            tablecxc_ac.setModel(modeloTabla_cxc);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            con.desconectar();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_abonar;
    public static javax.swing.JButton btn_agrega;
    public static javax.swing.JButton btn_anular_pago;
    public static javax.swing.JButton btn_modificar_reg;
    public javax.swing.JButton btn_search1;
    public static javax.swing.JButton btn_search2;
    public javax.swing.JButton btn_search5;
    public static javax.swing.JLabel cliente_id_hidden_ac;
    public static javax.swing.JLabel cxc_id_hidden_ac;
    public static javax.swing.JLabel funda_id_hidden_ac;
    public static com.toedter.calendar.JDateChooser jDateChooser1_ac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lb_codigo2;
    public static javax.swing.JLabel lb_producto;
    public static javax.swing.JLabel product_id_hidden_ac;
    public static javax.swing.JLabel pvp_con_iva;
    public static javax.swing.JLabel pvp_sin_iva;
    public static javax.swing.JTable tablecxc_ac;
    public static javax.swing.JTextField txt_abono;
    public static javax.swing.JTextField txt_celular_ac;
    public static javax.swing.JTextField txt_dirc_casa_ac;
    public static javax.swing.JTextField txt_direc_trabajo_ac;
    public static javax.swing.JTextField txt_email_ac;
    public static javax.swing.JTextField txt_fono_casa_ac;
    public static javax.swing.JTextField txt_fono_trabajo_ac;
    public static javax.swing.JTextField txt_names_ac;
    public static javax.swing.JTextField txt_nro_funda;
    public static javax.swing.JTextField valor_producto;
    // End of variables declaration//GEN-END:variables
}
