/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.BorderLayout;

/**
 *
 * @author Desarrollo
 */
public class views_usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form pruebas
     */
    public views_usuarios() {
        initComponents();
        rb_activo.setEnabled(false);
        rb_cedula_ruc.setEnabled(false);
        rb_inactivo.setEnabled(false);
        rb_passport.setEnabled(false);
        txt_RucDniPass.setEnabled(false);
        txt_apellido_user.setEnabled(false);
        txt_buscar.setEnabled(false);
        txt_celular_user.setEnabled(false);
        txt_clave_usr.setEnabled(false);
        txt_correo_user.setEnabled(false);
        txt_id_usuario.setEnabled(false);
        txt_nombreUser.setEnabled(false);
        txt_username_user.setEnabled(false);
        btn_actulizarDatos.setEnabled(false);
        btn_eliminarDatos.setEnabled(false);
        cmb_empleado_comedor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_estado = new javax.swing.ButtonGroup();
        group_identificacion = new javax.swing.ButtonGroup();
        panelhora = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_RucDniPass = new javax.swing.JTextField();
        txt_nombreUser = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_newDato = new javax.swing.JButton();
        btn_listarDatos = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_passport = new javax.swing.JRadioButton();
        rb_cedula_ruc = new javax.swing.JRadioButton();
        btn_actulizarDatos = new javax.swing.JButton();
        btn_eliminarDatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_apellido_user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_celular_user = new javax.swing.JTextField();
        txt_correo_user = new javax.swing.JTextField();
        txt_username_user = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_clave_usr = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txt_id_usuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rb_activo = new javax.swing.JRadioButton();
        rb_inactivo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        cmb_empleado_comedor = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NUEVO USUARIO");
        setToolTipText("");

        panelhora.setBackground(new java.awt.Color(255, 255, 255));
        panelhora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel1.setText("Cedula/RUC/PASS");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel2.setText("Nombre");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOTONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11), new java.awt.Color(0, 153, 204))); // NOI18N

        btn_newDato.setBackground(new java.awt.Color(0, 102, 204));
        btn_newDato.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_newDato.setForeground(new java.awt.Color(255, 255, 255));
        btn_newDato.setText("Nuevo");

        btn_listarDatos.setBackground(new java.awt.Color(51, 102, 0));
        btn_listarDatos.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_listarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btn_listarDatos.setText("Listar");

        btn_ok.setBackground(new java.awt.Color(102, 102, 255));
        btn_ok.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_ok.setText("Guardar");
        btn_ok.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_listarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_newDato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_newDato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(btn_listarDatos))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setText("BUSCAR");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel5.setText("Eliga la Opcion");

        group_identificacion.add(rb_passport);
        rb_passport.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rb_passport.setText("Pasaporte");

        group_identificacion.add(rb_cedula_ruc);
        rb_cedula_ruc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rb_cedula_ruc.setSelected(true);
        rb_cedula_ruc.setText("Cedula/RUC");

        btn_actulizarDatos.setBackground(new java.awt.Color(255, 204, 0));
        btn_actulizarDatos.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_actulizarDatos.setText("Actulizar");

        btn_eliminarDatos.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminarDatos.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btn_eliminarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminarDatos.setText("Inactivar");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Seleccione el usuario a editar o eliminar");

        tablaUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "DNI/Ruc/Pass", "Nombres", "Apellidos", "Celular", "Email", "Username", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel6.setText("Apellidos");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel8.setText("Celular");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel10.setText("Clave");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel11.setText("Id Usuario");

        txt_id_usuario.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel12.setText("Estado");

        group_estado.add(rb_activo);
        rb_activo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rb_activo.setSelected(true);
        rb_activo.setText("Activo");

        group_estado.add(rb_inactivo);
        rb_inactivo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rb_inactivo.setText("Inactivo");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel13.setText("Almacen");

        cmb_empleado_comedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sucursal", "Principal" }));

        javax.swing.GroupLayout panelhoraLayout = new javax.swing.GroupLayout(panelhora);
        panelhora.setLayout(panelhoraLayout);
        panelhoraLayout.setHorizontalGroup(
            panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelhoraLayout.createSequentialGroup()
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelhoraLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 91, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhoraLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_actulizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_eliminarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelhoraLayout.createSequentialGroup()
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhoraLayout.createSequentialGroup()
                                    .addComponent(rb_cedula_ruc)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_passport))
                                .addGroup(panelhoraLayout.createSequentialGroup()
                                    .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_RucDniPass, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nombreUser, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_celular_user, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel11))))
                            .addGroup(panelhoraLayout.createSequentialGroup()
                                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelhoraLayout.createSequentialGroup()
                                        .addComponent(rb_activo)
                                        .addGap(6, 6, 6)
                                        .addComponent(rb_inactivo))
                                    .addComponent(txt_username_user, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_clave_usr)
                            .addComponent(txt_apellido_user)
                            .addComponent(txt_correo_user)
                            .addGroup(panelhoraLayout.createSequentialGroup()
                                .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmb_empleado_comedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        panelhoraLayout.setVerticalGroup(
            panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelhoraLayout.createSequentialGroup()
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rb_passport)
                            .addComponent(rb_cedula_ruc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_RucDniPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_apellido_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_celular_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txt_correo_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(14, 14, 14)
                        .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_username_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(txt_clave_usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_activo)
                        .addComponent(rb_inactivo))
                    .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cmb_empleado_comedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_actulizarDatos)
                        .addComponent(btn_eliminarDatos))
                    .addComponent(jLabel3))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actulizarDatos;
    public javax.swing.JButton btn_eliminarDatos;
    public javax.swing.JButton btn_listarDatos;
    public javax.swing.JButton btn_newDato;
    public javax.swing.JButton btn_ok;
    public javax.swing.JComboBox cmb_empleado_comedor;
    public javax.swing.ButtonGroup group_estado;
    public javax.swing.ButtonGroup group_identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel panelhora;
    public javax.swing.JRadioButton rb_activo;
    public javax.swing.JRadioButton rb_cedula_ruc;
    public javax.swing.JRadioButton rb_inactivo;
    public javax.swing.JRadioButton rb_passport;
    public javax.swing.JTable tablaUsuarios;
    public javax.swing.JTextField txt_RucDniPass;
    public javax.swing.JTextField txt_apellido_user;
    public javax.swing.JTextField txt_buscar;
    public javax.swing.JTextField txt_celular_user;
    public javax.swing.JPasswordField txt_clave_usr;
    public javax.swing.JTextField txt_correo_user;
    public javax.swing.JTextField txt_id_usuario;
    public javax.swing.JTextField txt_nombreUser;
    public javax.swing.JTextField txt_username_user;
    // End of variables declaration//GEN-END:variables
}
